{% set pymomentum_cpu_gpu = "pymomentum-gpu" %}  # [cuda_compiler_version != "None"]
{% set pymomentum_cpu_gpu = "pymomentum-cpu" %}  # [cuda_compiler_version == "None"]
{% set name = "momentum" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/momentum/archive/v{{ version }}.tar.gz
    sha256: a447f4d6958be3078bb15110f1dcfb34355c06c9e9a80167a1e18e287cd07eb8
    patches:
      - 002-remove-pyproject-toml.patch
      - 003-add-setup-py.patch

build:
  number: 0
  skip: true  # [py<310]
  # cuda 11.8 was dropped due to maintenance effort
  skip: true  # [cuda_compiler_version == "11.8"]
  skip: true  # [ppc64le and cuda_compiler_version != "None"]
  skip: true  # [win and cuda_compiler_version != "None"]

outputs:
  - name: momentum-cpp
    script: build_cpp.sh  # [unix]
    script: bld_cpp.bat  # [win]
    build:
      skip:
        - true  # [cuda_compiler_version != "None"]
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
      ignore_run_exports:
        - ceres-solver
        - drjit-cpp
        - gflags
        - librerun-sdk
        - openfbx
        - re2
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - libboost-devel
        - cmake
        - gtest  # [build_platform == target_platform]
        - ninja  # [not win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - librerun-sdk
        - ms-gsl
        - nlohmann_json
        - openfbx
        - re2
        - spdlog
      run:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - ezc3d
        - fx-gltf
        - gflags
        - libdeflate
        - ms-gsl
        - nlohmann_json
        - openfbx
        - re2
    test:
      script: run_test_cpp.sh  # [unix]
      script: run_test_cpp.bat  # [win]
      requires:
        - cmake
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja  # [unix]
      files:
        - tests/
      commands:
        - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]

  - name: pymomentum
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      skip: true  # [win]
      skip: true  # [ppc64le]
      skip: true  # [aarch64 and cuda_compiler_version != "None"]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        {% if cuda_compiler_version != "None" %}
        - {{ compiler('cuda') }}
        - cuda-driver-dev           # [build_platform != target_platform]
        - cuda-cudart-dev           # [build_platform != target_platform]
        - cuda-nvrtc-dev            # [build_platform != target_platform]
        - cuda-nvtx-dev             # [build_platform != target_platform]
        - cuda-nvml-dev             # [build_platform != target_platform]
        - cuda-profiler-api         # [build_platform != target_platform]
        - libcublas-dev             # [build_platform != target_platform]
        - libcufft-dev              # [build_platform != target_platform]
        - libcurand-dev             # [build_platform != target_platform]
        - libcusolver-dev           # [build_platform != target_platform]
        - libcusparse-dev           # [build_platform != target_platform]
        {% endif %}
        - cmake
        - gtest
        - libboost-devel
        - ninja  # [not win]
        - pip
        - pybind11
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - setuptools
      host:
        # GPU requirements
        {% if cuda_compiler_version != "None" %}
        - cuda-version {{ cuda_compiler_version }}
        - cuda-driver-dev
        - cuda-cudart-dev
        - cuda-nvrtc-dev
        - cuda-nvtx-dev
        - cuda-nvml-dev
        - cuda-profiler-api
        - cudnn
        - libcublas-dev
        - libcufft-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - magma
        - nccl
        {% endif %}
        # other requirements
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - librerun-sdk
        - libtorch
        - ms-gsl
        - nlohmann_json
        - openfbx
        - python  # [linux]
        - re2
        - setuptools
        - spdlog
        - pip
        - python
        - pytorch
        - numpy
      run:
        # GPU requirements without run_exports
        - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != "None"]
        - ezc3d
        - dispenso
        - fmt
        - gflags
        - libdeflate
        - libtorch * cpu*   # [cuda_compiler_version == "None"]
        - libtorch * cuda*  # [cuda_compiler_version != "None"]
        - numpy
        - python
        - pytorch
        - re2
        - spdlog
    test:
      imports:
        - pymomentum.geometry
        - pymomentum.marker_tracking
        - pymomentum.quaternion
        - pymomentum.skel_state

  {% set pymomentum_cpu_gpu = "pymomentum-cpu" %}   # [cuda_compiler_version == "None"]
  {% set pymomentum_cpu_gpu = "pymomentum-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ pymomentum_cpu_gpu }}
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      detect_binary_files_with_prefix: false
      skip: true  # [win]
      skip: true  # [ppc64le]
      skip: true  # [aarch64 and cuda_compiler_version != "None"]
    requirements:
      run:
        - {{ pin_subpackage("pymomentum", exact=True) }}
    test:
      imports:
        - pymomentum.geometry
        - pymomentum.marker_tracking
        - pymomentum.quaternion
        - pymomentum.skel_state

  - name: momentum
    build:
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('momentum-cpp', exact=True) }}
        - {{ pin_subpackage('pymomentum', exact=True) }}  # [linux and not ppc64le]
        - {{ pin_subpackage('pymomentum', exact=True) }}  # [osx]
        - python
        - numpy
    test:
      commands:
        - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]

about:
  home: https://facebookincubator.github.io/momentum/
  summary: 'A library for human kinematic motion and numerical optimization solvers to apply human motion'
  description: |
    A library for human kinematic motion and numerical optimization solvers to apply human motion
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/momentum

extra:
  recipe-maintainers:
    - jeongseok-meta
