{% set pymomentum_cpu_gpu = "pymomentum-gpu" %}  # [cuda_compiler_version != "None"]
{% set pymomentum_cpu_gpu = "pymomentum-cpu" %}  # [cuda_compiler_version == "None"]
{% set name = "momentum" %}
{% set version = "0.1.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookincubator/momentum/archive/v{{ version }}.tar.gz
    sha256: b013deffdcf8a45f2adc27e96532696bedbe99762506bae2d09f9deca82e5b84
    patches:
      - patches/0001-Use-Python3-Module-instead-of-Python3_LIBRARIES.patch

build:
  number: 0
  skip: true  # [py<310]
  # cuda 11.8 was dropped due to maintenance effort
  skip: true  # [cuda_compiler_version == "11.8"]

outputs:
  - name: momentum-cpp
    script: build_cpp.sh  # [unix]
    script: bld_cpp.bat  # [win]
    build:
      skip:
        - true  # [cuda_compiler_version != "None"]
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
      ignore_run_exports:
        - ceres-solver
        - drjit-cpp
        - gflags
        - openfbx
        - re2
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - libboost-devel
        - cmake
        - gtest  # [build_platform == target_platform]
        - ninja  # [not win]
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - librerun-sdk <0.22
        - ms-gsl
        - nlohmann_json
        - openfbx
        - re2
        - spdlog
        - urdfdom
      run:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - ezc3d
        - fx-gltf
        - librerun-sdk <0.22
        - gflags
        - libdeflate
        - ms-gsl
        - nlohmann_json
        - openfbx
        - re2
    test:
      script: run_test_cpp.sh  # [unix]
      script: run_test_cpp.bat  # [win]
      requires:
        - cmake
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja  # [unix]
      files:
        - tests/
      commands:
        - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]
        - glb_viewer --help

  - name: pymomentum
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      skip: true  # [win and cuda_compiler_version != "None"]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        {% if cuda_compiler_version != "None" %}
        - {{ compiler('cuda') }}
        - cuda-toolkit
        - nvtx-c
        {% endif %}
        - cmake
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - gtest
        - libboost-devel
        - make
        - ninja  # [not win]
        - pip
        - pybind11
        - python
        - pytorch
        - scikit-build-core
      host:
        # GPU requirements
        {% if cuda_compiler_version != "None" %}
        - cuda-version {{ cuda_compiler_version }}
        - cuda-toolkit
        - nvtx-c
        {% endif %}
        # other requirements
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - librerun-sdk <0.22
        - libtorch
        - ms-gsl
        - nlohmann_json
        - numpy
        - openfbx
        - pip
        - python
        - pytorch
        - re2
        - scikit-build-core
        - spdlog
        - urdfdom
      run:
        - ezc3d
        - dispenso
        - fmt
        - gflags
        - libdeflate
        - pytorch
        - numpy
        - python
        - re2
        - spdlog
    test:
      imports:
        - pymomentum.geometry
        - pymomentum.marker_tracking
        - pymomentum.quaternion
        - pymomentum.skel_state
        - pymomentum.solver

  {% set pymomentum_cpu_gpu = "pymomentum-cpu" %}   # [cuda_compiler_version == "None"]
  {% set pymomentum_cpu_gpu = "pymomentum-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ pymomentum_cpu_gpu }}
    build:
      string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      detect_binary_files_with_prefix: false
      skip: true  # [win and cuda_compiler_version != "None"]
    requirements:
      run:
        - {{ pin_subpackage("pymomentum", exact=True) }}

  - name: momentum
    build:
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('momentum-cpp', exact=True) }}
        - {{ pin_subpackage('pymomentum', exact=True) }}
        - python

about:
  home: https://facebookincubator.github.io/momentum/
  summary: 'A library for human kinematic motion and numerical optimization solvers to apply human motion'
  description: |
    A library for human kinematic motion and numerical optimization solvers to apply human motion
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookincubator/momentum

extra:
  recipe-maintainers:
    - jeongseok-meta
