{% set pymomentum_cpu_gpu = "pymomentum-gpu" %}  # [cuda_compiler_version != "None"]
{% set pymomentum_cpu_gpu = "pymomentum-cpu" %}  # [cuda_compiler_version == "None"]
{% set name = "momentum" %}
{% set version = "0.1.102" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/facebookresearch/momentum/archive/v{{ version }}.tar.gz
    sha256: 5821eedb4ecabdb94315f6c20a9135b187b4668d5470da772efdec7e943d7079

build:
  number: 1
  # Skip Python < 3.12
  skip: true  # [py<312]

outputs:
  - name: momentum-cpp
    script: build_cpp.sh  # [unix]
    script: bld_cpp.bat  # [win]
    build:
      skip:
        - true  # [cuda_compiler_version != "None"]
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
      ignore_run_exports:
        - ceres-solver
        - drjit-cpp
        - gflags
        - openfbx
        - re2
        - tbb-devel  # Allow solver to pick tbb version compatible with libtorch/mkl
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - libboost-devel
        - cmake
        - gtest  # [build_platform == target_platform]
        - indicators
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - indicators
        - kokkos
        - librerun-sdk {{ rerun_version }}
        - ms-gsl
        - nlohmann_json
        - openfbx
        - openusd  # [linux]
        - python  # [linux]
        - re2
        - spdlog
        - tbb-devel  # [not win]
        - urdfdom
      run:
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - ezc3d
        - fx-gltf
        - indicators
        - libabseil  # [osx]
        - librerun-sdk {{ rerun_version }}
        - gflags
        - libdeflate
        - ms-gsl
        - nlohmann_json
        - openfbx
        - python  # [linux]
        - re2
        - tbb  # [linux]
    test:
      script: run_test_cpp.sh  # [unix]
      script: run_test_cpp.bat  # [win]
      requires:
        - cmake
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - ninja
      files:
        - tests/
      commands:
        - test -f $PREFIX/lib/cmake/momentum/momentum-config.cmake  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\cmake\\momentum\\momentum-config.cmake exit 1  # [win]
        - animate_shapes --help
        - c3d_viewer --help
        - convert_model --help
        - fbx_viewer --help
        - glb_viewer --help
        - hello_world
        - process_markers_app --help
        - refine_motion --help
        - urdf_viewer --help

  - name: pymomentum
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    build:
      string: cpu_py{{ CONDA_PY }}_pt{{ pytorch | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_pt{{ pytorch | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      # Internal DLLs bundled together that reference each other
      missing_dso_whitelist:   # [win]
        - "*/momentum_*.dll"  # [win]
        - "*/axel.dll"  # [win]
        # System NVIDIA driver (not available on Azure CI machines without GPU)
        - "*/nvcuda.dll"  # [win and cuda_compiler_version != "None"]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - {{ compiler('cuda') }}                        # [cuda_compiler_version != "None" and not win]
        - cuda-toolkit                                  # [cuda_compiler_version != "None" and not win]
        - cuda-version {{ cuda_compiler_version }}      # [cuda_compiler_version != "None" and win]
        - vs2022_win-64                                 # [cuda_compiler_version != "None" and win]
        - cuda-nvcc_win-64                              # [cuda_compiler_version != "None" and win]
        - cmake
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - gtest
        - indicators
        - libboost-devel
        - make
        - ninja
        - pip
        - pybind11-abi 11
        - python
        - pytorch
        - scikit-build-core >=0.11
      host:
        # GPU requirements
        - cuda-toolkit                                  # [cuda_compiler_version != "None" and not win]
        - cuda-version {{ cuda_compiler_version }}      # [cuda_compiler_version != "None"]
        - vs2022_win-64                                 # [cuda_compiler_version != "None" and win]
        # CUDA runtime/headers for both link & import time:
        - cuda-cudart-dev                               # [cuda_compiler_version != "None" and win]
        - cuda-cudart                                   # [cuda_compiler_version != "None"]
        - cuda-nvrtc-dev                                # [cuda_compiler_version != "None" and win]
        - cuda-nvrtc                                    # [cuda_compiler_version != "None"]
        - nvtx-c                                        # [cuda_compiler_version != "None"]
        - kokkos * *cuda*                               # [cuda_compiler_version != "None"]
        # other requirements
        - ceres-solver
        - cli11
        - dispenso
        - drjit-cpp
        - eigen
        - ezc3d
        - fmt
        - fx-gltf
        - indicators
        - kokkos
        - librerun-sdk {{ rerun_version }}
        - ms-gsl
        - nlohmann_json
        - numpy
        - openfbx
        - openusd  # [linux]
        - pip
        - pytest
        - python
        - pytorch
        - libtorch  # [unix]  # Provides torch/torch.h C++ headers
        - re2
        - scikit-build-core >=0.11
        - spdlog
        - tbb-devel  # [not win]
        - urdfdom
        - zlib
      run:
        # CUDA runtime needed at import time (no GPU required to import):
        - cuda-cudart                                   # [cuda_compiler_version != "None"]
        - cuda-nvrtc                                    # [cuda_compiler_version != "None"]
        # Kokkos CUDA variant needed for geometry module on CUDA builds
        - kokkos * *cuda*                               # [cuda_compiler_version != "None"]
        - ezc3d
        - dispenso
        - gflags
        - indicators
        - libabseil  # [osx]
        - libdeflate
        - pytorch
        - numpy
        - python
        - re2
        - spdlog
        - tbb  # [linux]
    test:
      imports:
        - pymomentum.axel
        # On Windows CUDA builds, geometry/backend require nvcuda.dll (NVIDIA driver)
        # which is not available on Azure build machines without GPUs
        - pymomentum.backend  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.geometry  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.diff_geometry  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.marker_tracking  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.quaternion
        - pymomentum.renderer  # [cuda_compiler_version == "None"]
        - pymomentum.skel_state
        - pymomentum.solver  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.solver2  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.torch.character  # [not (win and cuda_compiler_version != "None")]
        - pymomentum.trs
      commands:
        - pip list
        - pip check
      requires:
        - pip

  {% set pymomentum_cpu_gpu = "pymomentum-cpu" %}   # [cuda_compiler_version == "None"]
  {% set pymomentum_cpu_gpu = "pymomentum-gpu" %}   # [cuda_compiler_version != "None"]
  - name: {{ pymomentum_cpu_gpu }}
    build:
      string: cpu_py{{ CONDA_PY }}_pt{{ pytorch | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
      string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_pt{{ pytorch | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      detect_binary_files_with_prefix: false
    requirements:
      run:
        - {{ pin_subpackage("pymomentum", exact=True) }}

  - name: momentum
    build:
      run_exports:
        - {{ pin_subpackage('momentum-cpp', max_pin='x.x') }}
    requirements:
      run:
        - {{ pin_subpackage('momentum-cpp', exact=True) }}
        - {{ pin_subpackage('pymomentum', exact=True) }}
        - python

about:
  home: https://facebookresearch.github.io/momentum/
  summary: 'A library for human kinematic motion and numerical optimization solvers to apply human motion'
  description: |
    A library for human kinematic motion and numerical optimization solvers to apply human motion
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/facebookresearch/momentum

extra:
  recipe-maintainers:
    - jeongseok-meta
